##microsoft hosted agent and have issue with build artifacts 
---
  trigger:
    - main

  pool: 
    vmImage: ubuntu-22.04
    
  extends:
    template: generic-maven-java.yml
    parameters:
      javaVersion: '1.17'
      mavenGoal: 'package'
      artifactPath: '**/target/spring-petclinic*.jar'
      artifactName: 'SPCArtifacts'
    
    

