##microsoft hosted agent and have issue with build artifacts 
---
  trigger:
    - main
  variables:
    goals: package
  
  parameters:
    - name: MavenGoal
      displayName: MavenGoal
      type: string 
      default: package
      values:
        - package
        - clean package
        - install
        - clean install
  
  jobs:
    - job: build_job 
      displayName:  Buld and package Spring Pet Clinic Application
      pool: 
        vmImage: ubuntu-22.04
      steps:
        - task: Maven@3
          inputs: 
            mavenPOMFile: 'pom.xml'
            goals: ${{ parameters.MavenGoal }}
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
        - task: CopyFiles@2
          inputs: 
            Contents: "**/target/spring-petclinic*.jar"
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: SPCArtifacts
    

